import 'dart:io';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'package:splitter/Model/group_model.dart';
import 'package:splitter/Services/supabase_service.dart';

/// Exports group transaction data to CSV or PDF and shares via system sheet.
class ExportService {
  final _dateFormat = DateFormat('yyyy-MM-dd');
  final _dateTimeFormat = DateFormat('yyyy-MM-dd HH:mm');

  Future<void> exportGroupCsv({
    required String groupId,
    required String groupName,
    required String userId,
  }) async {
    final rows = await _loadTransactions(groupId, userId);
    if (rows.isEmpty) throw 'No transactions to export';

    final buffer = StringBuffer();
    buffer.writeln(
        'Date,Description,Category,Paid By,Shared With,Amount,Currency,Type');

    for (final t in rows) {
      buffer.writeln([
        _quote(_dateTimeFormat.format(t.transactionDate ?? DateTime.now())),
        _quote(t.description ?? ''),
        _quote(t.category ?? ''),
        _quote(t.paidByName ?? ''),
        _quote(t.sharedWithName ?? ''),
        (t.sharedTransactionAmount ?? t.totalTransactionAmount ?? 0)
            .toStringAsFixed(2),
        'INR',
        _quote(t.sharingType ?? 'expense'),
      ].join(','));
    }

    final file = await _writeTemp(
      'splito_${_safeName(groupName)}_${_dateFormat.format(DateTime.now())}.csv',
      buffer.toString(),
    );

    await Share.shareXFiles(
      [XFile(file.path)],
      subject: '$groupName — transaction export',
      text: 'SplitO export for $groupName',
    );
  }

  Future<void> exportGroupPdf({
    required String groupId,
    required String groupName,
    required String userId,
  }) async {
    final rows = await _loadTransactions(groupId, userId);
    if (rows.isEmpty) throw 'No transactions to export';

    double total = 0;
    for (final t in rows) {
      total += t.sharedTransactionAmount ?? t.totalTransactionAmount ?? 0;
    }

    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Header(
            level: 0,
            child: pw.Text(
              groupName,
              style: pw.TextStyle(
                fontSize: 22,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.Text('Exported ${DateFormat('MMM d, yyyy').format(DateTime.now())}'),
          pw.SizedBox(height: 8),
          pw.Text('Total rows: ${rows.length}'),
          pw.Text('Combined amount: ${total.toStringAsFixed(2)}'),
          pw.SizedBox(height: 16),
          pw.TableHelper.fromTextArray(
            headers: [
              'Date',
              'Description',
              'Paid By',
              'Amount',
              'Type',
            ],
            data: rows.map((t) {
              final amount =
                  t.sharedTransactionAmount ?? t.totalTransactionAmount ?? 0;
              return [
                _dateTimeFormat.format(t.transactionDate ?? DateTime.now()),
                t.description ?? '',
                t.paidByName ?? '',
                amount.toStringAsFixed(2),
                t.sharingType ?? 'expense',
              ];
            }).toList(),
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            cellAlignment: pw.Alignment.centerLeft,
            headerDecoration:
                const pw.BoxDecoration(color: PdfColors.grey300),
          ),
          pw.SizedBox(height: 24),
          pw.Text(
            'Generated by SplitO',
            style: const pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey600,
            ),
          ),
        ],
      ),
    );

    final bytes = await doc.save();
    final dir = await getTemporaryDirectory();
    final file = File(
      '${dir.path}/splito_${_safeName(groupName)}_${_dateFormat.format(DateTime.now())}.pdf',
    );
    await file.writeAsBytes(bytes);

    await Share.shareXFiles(
      [XFile(file.path)],
      subject: '$groupName — PDF export',
      text: 'SplitO PDF export for $groupName',
    );
  }

  Future<List<GroupTransactionModel>> _loadTransactions(
      String groupId, String userId) async {
    return SupabaseDatabase().getGroupTransactionsData(
      userID: userId,
      groupID: groupId,
    );
  }

  String _quote(String value) {
    final escaped = value.replaceAll('"', '""');
    return '"$escaped"';
  }

  String _safeName(String name) =>
      name.replaceAll(RegExp(r'[^\w]+'), '_').toLowerCase();

  Future<File> _writeTemp(String filename, String content) async {
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$filename');
    await file.writeAsString(content);
    return file;
  }
}
